#
# open-ortho orthanc v0.1.3
#
version: "2"
services:
  nginx-reverse-proxy:
    build: nginx
    container_name: nginx-reverse-proxy
    environment: 
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Rome"
    volumes: [
      "$<ORTHANC_CONFIG>/nginx/default.conf:/config/nginx/site-confs/default.conf:ro",
      "$<ORTHANC_CONFIG>/nginx-reverse-proxy/keys:/config/keys:rw"
    ]
    restart: unless-stopped
    ports: [
      "$<ORTHANC_IP>80:80",
      "$<ORTHANC_IP>443:443",
    ]
  orthanc:
    build: orthanc
    depends_on: [$<DATABASE_DOCKER_IMAGE>]
    restart: unless-stopped
    ports: [
      "$<ORTHANC_IP>104:4242"
      ]
    volumes: [
      orthanc-storage:/var/lib/orthanc/db:Z,
      "$<ORTHANC_CONFIG>/orthanc/orthanc.json:/etc/orthanc/orthanc.json:ro"
      ]
    environment: 
      VERBOSE_ENABLED: "false"
      VERBOSE_STARTUP: "false"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "YYYY-MM-DD"


  $<DATABASE_DOCKER_IMAGE>:
    image: postgres
    restart: unless-stopped
    volumes: [
      "$<POSTGRESQL_DATA>:/var/lib/postgresql/data:Z"
      ]
    environment:
      POSTGRES_PASSWORD: "postgres"

volumes:
  orthanc-storage:
    driver: local
    type: cifs
    device: //$<SMB_SERVER>/$<SMB_SHARE>
    o: "credentials=$<ORTHANC_CONFIG>/smbcredentials"
