#
# open-ortho orthanc v0.1.1
#
version: "2"
services:
  nginx-reverse-proxy:
    build: nginx
    container_name: nginx-reverse-proxy
    environment: 
      PUID: "1000"
      PGID: "1000"
      TZ: "Europe/Rome"
    volumes: [
      "$<ORTHANC_CONFIG>/nginx-reverse-proxy/site-confs:/config/nginx/site-confs:ro",
      "$<ORTHANC_CONFIG>/nginx-reverse-proxy/keys:/config/keys:ro"
    ]
    restart: unless-stopped
    ports: [
      "$<ORTHANC_IP>80:80",
      "$<ORTHANC_IP>443:443",
    ]
  orthanc:
    build: orthanc
    depends_on: [orthanc-index]
    restart: unless-stopped
    ports: [
      "$<ORTHANC_IP>104:4242"
      ]
    volumes: [
      "$<ORTHANC_DATA_MOUNT>/storage:/var/lib/orthanc/db:Z",
      "$<ORTHANC_CONFIG>/orthanc.production.json:/etc/orthanc/orthanc.json:ro"
      ]
    environment: 
      VERBOSE_ENABLED: "false"
      VERBOSE_STARTUP: "false"
      OSIMIS_WEB_VIEWER1_PLUGIN_ENABLED: "true"
      STONE_WEB_VIEWER_PLUGIN_ENABLED: "true"
      DICOM_WEB_PLUGIN_ENABLED: "true"
      ORTHANC__STONE_WEB_VIEWER__DATE_FORMAT: "YYYY-MM-DD"


  orthanc-index:
    image: postgres
    restart: unless-stopped
    volumes: [
      "$<POSTGRESQL_DATA>:/var/lib/postgresql/data:Z"
      ]
    environment:
      POSTGRES_PASSWORD: "postgres"
