name: build-dist-package
on:
  workflow_dispatch:
    
  push:
    branches:
      - 'release/**'
      - '!release/**-dev'
jobs:
  build-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make tarball
        run: make tarball
      
      - name: Make GitHub Release
        run: make github-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}