name: build-dist-package
on:
  workflow_dispatch:
    
  push:
    branches:
      - 'release/**'
      - '!release/**-dev'
jobs:
  build-tarball:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-node@v2
        with: 
          node-version: 14

      - name: Configure GitHub CLI with GitHub Token
        run: |
          echo "machine github.com login zgypa password ${{ github.token }}" >> ~/.netrc
          gh auth login --with-token < "${HOME}/.netrc"

      - name: Install GitHub CLI
        run: npm install -g gh

      - name: Make tarball
        run: make tarball
      
      - name: Make GitHub Release
        run: make github-release